FROM eclipse-temurin:18

WORKDIR /app

COPY backend-bobs-bargain-0.0.2-docker.jar /app/backend-bobs-bargain-0.0.2-docker.jar

EXPOSE 4000

ENTRYPOINT ["java", "-jar", "backend-bobs-bargain-0.0.2-docker.jar"]
